### PR TITLE
Drop package log15/stack in favor of github.com/go-stack/stack.

### PR DESCRIPTION
**Pull request by ChrisHines**
This is a **breaking change** because the name and type of an exported field change (`Record.CallPC` -> `Record.Call`). The next tagged release after this PR gets merged should increment the major version number.

The migration to the new stack dependency was very easy and allowed for simplifications in the associated handler code.

### CODE REVIEW

**Comment by ChrisHines** [comment]
This fixes #77 by deleting the package with failing tests.

**Comment by ChrisHines** [comment]
Also fixes #34.

**Comment by ChrisHines** [comment]
Also fixes #28.

**Comment by inconshreveable** [comment]
LGTM

**Pull request merged**
