### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by GeertJohan**
I wrote a simple changelog structure and added Loggly on the list. I suppose the changelog will start logging now, or does someone want to go back and write down all historical changes? :open_mouth:

### CODE REVIEW

**Comment by GeertJohan** [comment]
Forgot to add, it will look like this: https://gist.github.com/GeertJohan/c18cd89ddfc506e16c60

**Comment by GeertJohan** [comment]
TODO: Add #34 migration notes

**Comment by RobLoach** [comment]
http://keepachangelog.com is another good history spec.

**Comment by inconshreveable** [comment]
I think we'll keep this in the README.md for now where it's very visible. We can break it out into a separate file later if it gets overwhelming. For now, I'm only documenting breaking changes, but if anyone wants to contribute a second changelog of non-breaking changes (both improvements or additions) - I'd be happy to accept those PRs.

**Pull request closed without merging**
