### PR TITLE
Use atomic.Value instead of unsafe pointer swapping

### PR DESCRIPTION
**Pull request by titanous**
I *think* this will work on AppEngine, but I don't have an account to test it out. @karalabe any chance you can verify this?

### CODE REVIEW

**Comment by inconshreveable** [comment]
It's also worth noting that this will only work on appengine with go1.4 and greater. Does anyone know if appengine forces you to go1.4 or can you pick?

**Comment by karalabe** [comment]
Currently the default runtime for GAE is 1.2, with the possibility to switch to 1.4 (1.4beta tag version). The issue is that the goapp sdk is currently stuck at 1.2 and doesn't notice it that you're actually deploying an 1.4 app ([issue](https://groups.google.com/forum/#!topic/google-appengine-go/WeO8KGx6O8c)). The result is that it uploads 1.2 dependencies, which fail while compiling (or vice versa). Apparently this was fixed but has not yet landed publicly, so I'd hold on while it comes out not to muck up the codebase.

**Comment by inconshreveable** [comment]
Yeah, I don't think we can merge this in until appengine deprecates support for 1.2. Also this is not safe to merge in in the general case since it will break on non-GAE builds at <go1.4.

That said, when possible I'd like to merge this in since it's safer than using unsafe and faster than using locks for GAE.

**Comment by titanous** [comment]
Okay, want me to refactor and just replace the use of unsafe pointers and leave the appengine stuff alone?

**Comment by inconshreveable** [comment]
sounds good but we'd need another file with guards for just go1.4 for the atomic.Value stuff.

**Comment by titanous** [comment]
Ah, do you have a policy for how many past versions of Go are supported? Also, it would be nice to have Travis (or another public CI tool) testing them.

**Comment by inconshreveable** [comment]
Agreed, automated CI would be nice to set up. I'll open an issue for that. There's no policy right now on previous version support beyond, "as far back as possible without being a pain" which seems to be back to go1.1 for this library at least

**Comment by titanous** [comment]
Updated, though it needs a sanity check on appengine (1.2, 1.4) and Go <1.4

**Comment by inconshreveable** [comment]
awesome, thanks! works fine on go1.3. if it works on GAE we can merge it in

**Comment by inconshreveable** [comment]
@karalabe Do you have any bandwidth to verify this on GAE?

**Comment by karalabe** [comment]
GAE just (week or so) switched over to Go 1.4 by default on App Engine. I'm in the middle of something right now, but I'll try to take a look at it after I'm done.

**Comment by inconshreveable** [comment]
Awesome, thank you!

**Comment by ChrisHines** [comment]
@karalabe Has this been verified?

**Comment by ChrisHines** [comment]
The App Engine docs online say it now uses Go 1.6. I think this is safe to merge now.

**Comment by inconshreveable** [comment]
@ChrisHines looks like we should remove the special appengine behavior then if they support atomic.Value?

**Comment by ChrisHines** [comment]
That makes sense.

**Comment by inconshreveable** [comment]
K, I'll make that change and commit this.

**Comment by inconshreveable** [comment]
accepted via rebase, closing

**Pull request closed without merging**
