### PR TITLE
fix #123 by flagging the darwin build with !appengine as well

### LINKED ISSUE #123: failed build on app engine
Reported failure here: https://github.com/kevinburke/rest/pull/4#issuecomment-277801954

I've been unable to reproduce it, because you can't specify `GOOS=appengine` and compile the build. Need to set up the App Engine SDK locally and test using that OS.

If I had to guess, I would guess that App Engine is not a subset of `linux` and so the terminal_notwindows.go file also compiles there.

### PR DESCRIPTION
**Pull request by andrewwatson**

### CODE REVIEW

**Comment by inconshreveable** [comment]
shouldn't the darwin file not be included on appengine builds just by having the `_darwin.go` suffix? am I missing something?

**Comment by andrewwatson** [comment]
only when you deploy it to GCP.  when you're developing locally on your mac it uses the darwin file.

**Comment by inconshreveable** [comment]
ahh makes sense

**Comment by kevinburke** [comment]
I think we need a newline between the build flag and the comment? If this works, great, but not sure it will

**Comment by kevinburke** [comment]
Oh, nvm, you need a newline afterwards

**Pull request merged**
